name: "\U0001F41E Bug report"
description: Report an issue with Flowbite-Svelte
labels: ["triage: bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is. If you intend to submit a PR for this issue, tell us in the description. Thanks!
      placeholder: Bug description
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction
      description: Please provide a link to a repo or REPL that can reproduce the problem you ran into. If a report is vague (e.g. just a generic error message) and has no reproduction, it will receive a "need reproduction" label. If no reproduction is provided within a reasonable time-frame, the issue will be closed.
      placeholder: Reproduction
    validations:
      required: true
   - type: textarea
    id: flowbite-svelte-info
    attributes:
      label: Flowbite-Svelte Info
      description: Flowbite-Svelte version from your package.json. Are you using the latest version? Use `npm i -D flowbite-svelte@latest` to update and check the problem before submitting this issue please.
      placeholder: flowbite-svelte: vx.xx.xx
    validations:
      required: true
  - type: textarea
    id: system-info
    attributes:
      label: System Info
      description: Output of `npx envinfo --system --npmPackages svelte,rollup,webpack --binaries --browsers`
      render: shell
      placeholder: System, Binaries, Browsers
    validations:
      required: true